import { GirolandoBullData } from "./GirolandoBullDetailPage"

// Standard ABCZ traits (same for all bulls)
const standardAbczTraits = [
  { trait: "ALTG", pta: "--", conf: "--" },
  { trait: "COMP", pta: "--", conf: "--" },
  { trait: "PERT", pta: "--", conf: "--" },
  { trait: "ANGG", pta: "--", conf: "--" },
  { trait: "COMG", pta: "--", conf: "--" },
  { trait: "LIL", pta: "--", conf: "--" },
  { trait: "LIS", pta: "--", conf: "--" },
  { trait: "POSL", pta: "--", conf: "--" },
  { trait: "POST", pta: "--", conf: "--" },
  { trait: "ANGC", pta: "--", conf: "--" },
  { trait: "PU", pta: "--", conf: "--" },
  { trait: "LUP", pta: "--", conf: "--" },
  { trait: "LA", pta: "--", conf: "--" },
  { trait: "COMPT", pta: "--", conf: "--" },
  { trait: "AUP", pta: "--", conf: "--" },
  { trait: "LC", pta: "--", conf: "--" },
  { trait: "DIATE", pta: "--", conf: "--" },
  { trait: "TEMP", pta: "--", conf: "--" },
  { trait: "FAC ORD", pta: "--", conf: "--" },
  { trait: "UMBIGO", pta: "--", conf: "--" },
  { trait: "PELE", pta: "--", conf: "--" },
]

// Empty PNMGL data for bulls in test
const emptyPnmglData = [
  { trait: "Leite", pta: "--", conf: "--" },
  { trait: "Idade ao Primeiro Parto", pta: "--", conf: "--" },
  { trait: "NF", pta: "--", conf: "--" },
  { trait: "NR", pta: "--", conf: "--" },
  { trait: "Gordura Kg", pta: "--", conf: "--" },
  { trait: "Gordura %", pta: "--", conf: "--" },
  { trait: "Proteína Kg", pta: "--", conf: "--" },
  { trait: "Proteína %", pta: "--", conf: "--" },
  { trait: "Sólidos Totais Kg", pta: "--", conf: "--" },
  { trait: "Sólidos Totais %", pta: "--", conf: "--" },
]

export const girolandoBullsData: Record<string, GirolandoBullData> = {
  nemoday: {
    id: "nemoday",
    code: "001G000050",
    name: "NEMO DAY",
    fullName: "LLA NEMO 370 CAPELA DAY",
    registro: "0025-BT",
    nasc: "22/11/2020",
    criador: "LEONARDO DE LIMA AVELAR",
    proprietario: "LEONARDO DE LIMA AVELAR",
    lactacaoMae: "17.178 kg em 365 dias",
    ptaLeite: "EM TESTE - 2030",
    betaCaseina: "A2A2",
    kappaCaseina: "--",
    betaLacto: "--",
    imageUrl: "/NEMO_DAY_PHOTO.jpg",
    hasGenChoice: false,
    hasToro2A2: true,
    hasEmTeste: true,
    hasGenomico: true,
    pmggData: [
      { trait: "PTA Leite", pta: "--", conf: "--" },
      { trait: "PTA Leite Genômico", pta: "1.746", conf: "76" },
      { trait: "Intervalo de Parto", pta: "6", conf: "51" },
      { trait: "Idade Primeiro Parto", pta: "-36", conf: "68" },
      { trait: "Longevidade", pta: "1,30", conf: "49" },
      { trait: "TE", pta: "--", conf: "--" },
      { trait: "GPTA PN", pta: "0", conf: "75" },
      { trait: "GPTA PG", pta: "2,90", conf: "94" },
      { trait: "IPPLG", pta: "0,10", conf: "--" },
      { trait: "IETG", pta: "1,10", conf: "--" },
      { trait: "IFPG", pta: "0,40", conf: "--" },
      { trait: "IRG", pta: "-0,10", conf: "--" },
      { trait: "CPLFG", pta: "-0,10", conf: "--" },
    ],
    progenieData: {
      nf: "--",
      nr: "--",
    },
    pnmglData: emptyPnmglData,
    abczData: standardAbczTraits,
    pedigree: {
      title: "LLA NEMO 370 CAPELA DAY x CAPELA FIV CE BALS",
      sire: {
        name: "MR EVERGREENVIEW ALTADAY-ET",
        registro: "",
        siresSire: "SEAGULL-BAY SUPERSIRE-ET",
        siresDam: "AMMON-PEACHEY SHAUNA-ET",
      },
      dam: {
        name: "CAPELA FIV CE BALS",
        registro: "",
        damsSire: "REGANCREST-GV S BRADNICK-ET",
        damsDam: "HELOISA FIV KENYO",
      },
    },
  },
}
