import { Girolando58BullData } from "./Girolando58BullDetailPage"

export const girolando58BullsData: Record<string, Girolando58BullData> = {
  comandante: {
    id: "comandante",
    code: "001G000051",
    name: "COMANDANTE",
    fullName: "COMANDANTE FIV DA PRATA JAC",
    registro: "9701-BV",
    nasc: "05/04/2020",
    criador: "JOSÉ ANTÔNIO DA SILVA CLEMENTE",
    proprietario: "JOSÉ ANTÔNIO DA SILVA CLEMENTE",
    lactacaoMae: "8.631,79 Kg em 365 dias",
    ptaLeite: "EM TESTE",
    betaCaseina: "A2A2",
    kappaCaseina: "AB",
    betaLacto: "--",
    imageUrl: "/COMANDANTE_PHOTO.jpg",
    hasGenChoice: false,
    hasToro2A2: true,
    hasEmTeste: false,
    hasGenomico: true,
    pmggData: [
      { trait: "PTA Leite", pta: "--", conf: "--" },
      { trait: "PTA Leite Genômico", pta: "1.008", conf: "73" },
      { trait: "Intervalo de Parto", pta: "4", conf: "43" },
      { trait: "Idade Primeiro Parto", pta: "-11", conf: "66" },
      { trait: "Longevidade", pta: "1,30", conf: "54" },
      { trait: "TE", pta: "--", conf: "--" },
      { trait: "GPTA PN", pta: "-0,50", conf: "65" },
      { trait: "GPTA PG", pta: "-0,30", conf: "84" },
      { trait: "IPPLG", pta: "0,20", conf: "--" },
      { trait: "IETG", pta: "0,70", conf: "--" },
      { trait: "IFPG", pta: "-0,90", conf: "--" },
      { trait: "IRG", pta: "-0,40", conf: "--" },
      { trait: "CPLFG", pta: "0,40", conf: "--" },
    ],
    progenieData: {
      nf: "--",
      nr: "--",
    },
    pedigree: {
      title: "VINEYARD x QUERO-QUERO",
      sire: {
        name: "DELTA VINEYARD",
        registro: "",
        siresSire: "DELTA MAGISTER",
        siresDam: "DELTA JAZZ",
      },
      dam: {
        name: "HARMONIA TERRA VERMELHA",
        registro: "",
        damsSire: "C.A. QUERO-QUERO",
        damsDam: "QUARTINHA TERRA VERMELHA",
      },
    },
  },
  epico: {
    id: "epico",
    code: "001G010052",
    name: "ÉPICO (PS)",
    fullName: "ÉPICO EXCEÇÃO ELO FIV DA FORTALEZA",
    registro: "5015-CC",
    nasc: "14/03/2022",
    criador: "NOVOTEMPO AGRO LTDA",
    proprietario: "NOVOTEMPO AGRO LTDA",
    lactacaoMae: "14.557 kg em 365 dias",
    ptaLeite: "EM TESTE",
    betaCaseina: "A2A2",
    kappaCaseina: "--",
    betaLacto: "--",
    imageUrl: "/EPICO_PS_PHOTO.jpg",
    hasGenChoice: false,
    hasToro2A2: true,
    hasEmTeste: false,
    hasGenomico: true,
    pmggData: [
      { trait: "PTA Leite", pta: "--", conf: "--" },
      { trait: "PTA Leite Genômico", pta: "1.493", conf: "71" },
      { trait: "Intervalo de Parto", pta: "13", conf: "37" },
      { trait: "Idade Primeiro Parto", pta: "-8", conf: "60" },
      { trait: "Longevidade", pta: "1,40", conf: "46" },
      { trait: "TE", pta: "--", conf: "--" },
      { trait: "GPTA PN", pta: "0,20", conf: "61" },
      { trait: "GPTA PG", pta: "1,60", conf: "84" },
      { trait: "IPPLG", pta: "0,80", conf: "--" },
      { trait: "IETG", pta: "1", conf: "--" },
      { trait: "IFPG", pta: "0,30", conf: "--" },
      { trait: "IRG", pta: "0,60", conf: "--" },
      { trait: "CPLFG", pta: "1,30", conf: "--" },
    ],
    progenieData: {
      nf: "--",
      nr: "--",
    },
    pedigree: {
      title: "ELO SUPERSIRE x SHOTTLE",
      sire: {
        name: "ELO SUPERSIRE FIV KUB",
        registro: "",
        siresSire: "SEAGULL-BAY SUPERSIRE-ET",
        siresDam: "MINEIRA TEATRO FIV RPM DA S.ANTONIO",
      },
      dam: {
        name: "EXCEÇÃO SHOTTLE FIV RDM5",
        registro: "",
        damsSire: "PICSTON SHOTTLE-ET",
        damsDam: "LARANJA SANTA LUZIA",
      },
    },
  },
}
