import { GuzeraBullData } from "./GuzeraBullDetailPage"

export const guzeraBullsData: Record<string, GuzeraBullData> = {
  preferido: {
    id: "preferido",
    code: "001GT00004",
    name: "PREFERIDO",
    fullName: "PREFERIDO DA JUZZA",
    registro: "JUZZ 110",
    nasc: "23/12/2015",
    criador: "JULIANA PISTORE RAGAZZI",
    proprietario: "JULIANA PISTORE RAGAZZI",
    lactacaoMae: "3.659 no 1° parto",
    ptaLeite: "EM TESTE DE PROGÉNIE",
    betaCaseina: "A2A2",
    kappaCaseina: "--",
    betaLacto: "--",
    imageUrl: "/PREFERIDO_PHOTO.jpg",
    hasGenChoice: false,
    hasToro2A2: true,
    hasEmTeste: true,
    hasGenomico: false,
    pedigree: {
      title: "RUSSO x HUMAITÁ",
      sire: {
        name: "RUSSO TE JF",
        registro: "",
        siresSire: "URUTU",
        siresDam: "BANQUETA JF",
      },
      dam: {
        name: "ELEGANTE",
        registro: "",
        damsSire: "HUMAITA TE TABOO.",
        damsDam: "DUCHA MRM",
      },
    },
  },
  principe: {
    id: "principe",
    code: "001GT00007",
    name: "PRÍNCIPE",
    fullName: "PRÍNCIPE JF",
    registro: "JFT 4419",
    nasc: "11/03/2021",
    criador: "ANDERSON FABIANO MARQUES E FERNANDO VIEIRA DA CUNHA",
    proprietario: "ANDERSON FABIANO MARQUES E FERNANDO VIEIRA DA CUNHA",
    lactacaoMae: "--",
    ptaLeite: "EM TESTE DE PROGÉNIE",
    betaCaseina: "--",
    kappaCaseina: "--",
    betaLacto: "--",
    imageUrl: "/PRINCIPE_PHOTO.jpg",
    hasGenChoice: false,
    hasToro2A2: false,
    hasEmTeste: true,
    hasGenomico: false,
    pedigree: {
      title: "OPIO x OBRA",
      sire: {
        name: "OPIO FIV JF",
        registro: "",
        siresSire: "PERSEU 5",
        siresDam: "NÉGA TE JF",
      },
      dam: {
        name: "OBRA FIV JF",
        registro: "",
        damsSire: "ESTILETE DA MS",
        damsDam: "MALTA II JF",
      },
    },
  },
}
