import { GyrBullData } from "./GyrBullDetailPage"

// Standard ABCZ traits (same for all bulls)
const standardAbczTraits = [
  { trait: "ALTG", pta: "--", conf: "--" },
  { trait: "COMP", pta: "--", conf: "--" },
  { trait: "PERT", pta: "--", conf: "--" },
  { trait: "ANGG", pta: "--", conf: "--" },
  { trait: "COMG", pta: "--", conf: "--" },
  { trait: "LIL", pta: "--", conf: "--" },
  { trait: "LIS", pta: "--", conf: "--" },
  { trait: "POSL", pta: "--", conf: "--" },
  { trait: "POST", pta: "--", conf: "--" },
  { trait: "ANGC", pta: "--", conf: "--" },
  { trait: "PU", pta: "--", conf: "--" },
  { trait: "LUP", pta: "--", conf: "--" },
  { trait: "LA", pta: "--", conf: "--" },
  { trait: "COMPT", pta: "--", conf: "--" },
  { trait: "AUP", pta: "--", conf: "--" },
  { trait: "LC", pta: "--", conf: "--" },
  { trait: "DIATE", pta: "--", conf: "--" },
  { trait: "TEMP", pta: "--", conf: "--" },
  { trait: "FAC ORD", pta: "--", conf: "--" },
  { trait: "UMBIGO", pta: "--", conf: "--" },
  { trait: "PELE", pta: "--", conf: "--" },
]

// Empty PNMGL data for bulls in test
const emptyPnmglData = [
  { trait: "Leite", pta: "--", conf: "--" },
  { trait: "Idade ao Primeiro Parto", pta: "--", conf: "--" },
  { trait: "NF", pta: "--", conf: "--" },
  { trait: "NR", pta: "--", conf: "--" },
  { trait: "Gordura Kg", pta: "--", conf: "--" },
  { trait: "Gordura %", pta: "--", conf: "--" },
  { trait: "Proteína Kg", pta: "--", conf: "--" },
  { trait: "Proteína %", pta: "--", conf: "--" },
  { trait: "Sólidos Totais Kg", pta: "--", conf: "--" },
  { trait: "Sólidos Totais %", pta: "--", conf: "--" },
]

export const gyrBullsData: Record<string, GyrBullData> = {
  edank: {
    id: "edank",
    code: "001GL00051",
    name: "EDANK",
    fullName: "EDANK TE JABAQUARA",
    registro: "EVPF444",
    nasc: "09/08/2013",
    criador: "ELIO VIRGINIO PIMENTEL - FAZENDA JABAQUARA",
    proprietario: "AGROPECUÁRIA JABAQUARA LTDA, ESTÂNCIA QUALYTÃ E GENEX BRASIL",
    lactacaoMae: "20,018 Kg em 365 dias",
    ptaLeite: "PROVADO PTAL: 888",
    betaCaseina: "A1A2",
    kappaCaseina: "AB",
    betaLacto: "BB",
    imageUrl: "/EDANK_PROFILE.jpg",
    hasGenChoice: true,
    hasToro2A2: false,
    pnmglData: [
      { trait: "Leite", pta: "888", conf: "87" },
      { trait: "Idade ao Primeiro Parto", pta: "-56", conf: "82" },
      { trait: "NF", pta: "15", conf: "--" },
      { trait: "NR", pta: "8", conf: "--" },
      { trait: "Gordura Kg", pta: "--", conf: "--" },
      { trait: "Gordura %", pta: "--", conf: "--" },
      { trait: "Proteína Kg", pta: "--", conf: "--" },
      { trait: "Proteína %", pta: "--", conf: "--" },
      { trait: "Sólidos Totais Kg", pta: "--", conf: "--" },
      { trait: "Sólidos Totais %", pta: "--", conf: "--" },
    ],
    abczData: standardAbczTraits,
  },
  trovao: {
    id: "trovao",
    code: "001GL00054",
    name: "TROVÃO 2B",
    fullName: "TROVAO 2B",
    registro: "ZAB1044",
    nasc: "10/07/2014",
    criador: "JOSÉ AFONSO BICALHO B. DA SILVA",
    proprietario: "JOSÉ AFONSO BICALHO B. DA SILVA",
    lactacaoMae: "11,764 Kg em 365 dias",
    ptaLeite: "PROVADO PTAL: 721",
    betaCaseina: "A2A2",
    kappaCaseina: "AA",
    betaLacto: "AB",
    imageUrl: "/GYR_TROVAO.jpg",
    hasGenChoice: true,
    hasToro2A2: true,
    pnmglData: [
      { trait: "Leite", pta: "721", conf: "87" },
      { trait: "Idade ao Primeiro Parto", pta: "-140", conf: "82" },
      { trait: "NF", pta: "3", conf: "--" },
      { trait: "NR", pta: "2", conf: "--" },
      { trait: "Gordura Kg", pta: "31", conf: "76" },
      { trait: "Gordura %", pta: "0,16", conf: "70" },
      { trait: "Proteína Kg", pta: "15", conf: "75" },
      { trait: "Proteína %", pta: "0,10", conf: "81" },
      { trait: "Sólidos Totais Kg", pta: "35", conf: "70" },
      { trait: "Sólidos Totais %", pta: "0,33", conf: "71" },
    ],
    abczData: standardAbczTraits,
  },
  beneton: {
    id: "beneton",
    code: "001GL00069",
    name: "BENETON",
    fullName: "BENETON FIV 2B",
    registro: "ZAB 1762",
    nasc: "09/03/2018",
    criador: "JOSÉ AFONSO BICALHO B. DA SILVA",
    proprietario: "JOSÉ AFONSO BICALHO B. DA SILVA / IRACI DE ASSIS CUNHA",
    lactacaoMae: "10,409 Kg em 365 dias",
    ptaLeite: "EM TESTE DE PROGÊNIE - 2027",
    betaCaseina: "A2A2",
    kappaCaseina: "AA",
    betaLacto: "BB",
    imageUrl: "/GYR_BENETON.jpg",
    hasGenChoice: false,
    hasToro2A2: true,
    pnmglData: emptyPnmglData,
    abczData: standardAbczTraits,
  },
  elvis: {
    id: "elvis",
    code: "001GL00078",
    name: "ELVIS",
    fullName: "ELVIS DA ESTANCIA K",
    registro: "BRAN327",
    nasc: "29/11/2020",
    criador: "LUIZ EDUARDO BRANQUINHO",
    proprietario: "LUIZ EDUARDO BRANQUINHO",
    lactacaoMae: "10,401 Kg em 365 dias",
    ptaLeite: "EM TESTE DE PROGÊNIE - 2030",
    betaCaseina: "A2A2",
    kappaCaseina: "AA",
    betaLacto: "AB",
    imageUrl: "/GYR_ELVIS.jpg",
    hasGenChoice: true,
    hasToro2A2: true,
    pnmglData: emptyPnmglData,
    abczData: standardAbczTraits,
  },
  uno: {
    id: "uno",
    code: "001GL00063",
    name: "UNO 2B",
    fullName: "UNO 2B",
    registro: "ZAB1140",
    nasc: "20/05/2015",
    criador: "JOSÉ AFONSO BICALHO B. DA SILVA",
    proprietario: "JOSÉ AFONSO BICALHO B. DA SILVA",
    lactacaoMae: "9,355 Kg em 365 dias",
    ptaLeite: "PROVADO PTAL: 857",
    betaCaseina: "A2A2",
    kappaCaseina: "AA",
    betaLacto: "AA",
    imageUrl: "/GYR_UNO.jpg",
    hasGenChoice: false,
    hasToro2A2: true,
    pnmglData: [
      { trait: "Leite", pta: "857", conf: "86" },
      { trait: "Idade ao Primeiro Parto", pta: "-89", conf: "81" },
      { trait: "NF", pta: "2", conf: "--" },
      { trait: "NR", pta: "2", conf: "--" },
      { trait: "Gordura Kg", pta: "42", conf: "77" },
      { trait: "Gordura %", pta: "0,05", conf: "71" },
      { trait: "Proteína Kg", pta: "22", conf: "75" },
      { trait: "Proteína %", pta: "0", conf: "82" },
      { trait: "Sólidos Totais Kg", pta: "48", conf: "68" },
      { trait: "Sólidos Totais %", pta: "0,09", conf: "70" },
    ],
    abczData: standardAbczTraits,
  },
  eden: {
    id: "eden",
    code: "001GL00077",
    name: "ÉDEN",
    fullName: "ÉDEN FIV 2B",
    registro: "ZAB2466",
    nasc: "19/07/2021",
    criador: "JOSÉ AFONSO BICALHO B. DA SILVA",
    proprietario: "JOSÉ AFONSO BICALHO B. DA SILVA / IRACI DE ASSIS CUNHA / SILVIO QUEIROZ PINHEIRO",
    lactacaoMae: "13,068 Kg em 305 dias",
    ptaLeite: "EM TESTE DE PROGÊNIE - 2030",
    betaCaseina: "A2A2",
    kappaCaseina: "AA",
    betaLacto: "AB",
    imageUrl: "/GYR_EDEN.jpg",
    hasGenChoice: true,
    hasToro2A2: true,
    pnmglData: emptyPnmglData,
    abczData: standardAbczTraits,
  },
}
