import { NeloreBullData } from "./NeloreBullDetailPage"

export const neloreBullsData: Record<string, NeloreBullData> = {
  trembala: {
    id: "trembala",
    code: "001NE00749",
    name: "TREM BALA",
    fullName: "TREM BALA DA EAO",
    serieRgd: "EAU B1828",
    nasc: "26/08/2019",
    proprietario: "EÃO - EMPREENDIMENTOS AGROPECUÁRIOS E OBRAS S/A / GENEX BRASIL / EDUARDO DA COSTA",
    imageUrl: "/TREM_BALA_PHOTO.jpg",
    pregcheckBr: "100",
    pregcheckConf: "95",
    badges: ["MATERNAL", "CARCAÇA", "PRECOCIDADE SEXUAL"],
    progenieData: {
      nf120: "2.041",
      nr120: "121",
      nf450: "445",
      nr450: "36",
    },
    indiceData: {
      mgte: { top: "--", dep: "23,76", ac: "82" },
    },
    producaoData: [
      { trait: "PN", top: "97", dep: "1,71", ac: "94" },
      { trait: "P120", top: "6", dep: "7,70", ac: "91" },
      { trait: "P210", top: "7", dep: "12,61", ac: "91" },
      { trait: "P365", top: "8", dep: "21,92", ac: "90" },
      { trait: "P450", top: "5", dep: "25,77", ac: "90" },
      { trait: "PAV", top: "48", dep: "31,50", ac: "32" },
    ],
    maternalData: [
      { trait: "MP120", top: "1", dep: "6,09", ac: "48" },
      { trait: "MP210", top: "1", dep: "8", ac: "47" },
      { trait: "IPP", top: "6", dep: "-1,04", ac: "43" },
      { trait: "3P", top: "62", dep: "71,49", ac: "82" },
      { trait: "STAY", top: "7", dep: "86,56", ac: "79" },
      { trait: "PAC", top: "3", dep: "11,25", ac: "28" },
      { trait: "PE365", top: "21", dep: "0,64", ac: "84" },
    ],
    carcacaData: [
      { trait: "AOL", top: "8", dep: "3,10", ac: "90" },
      { trait: "ACAB", top: "7", dep: "0,47", ac: "89" },
      { trait: "MARM", top: "16", dep: "0,05", ac: "88" },
      { trait: "MAC", top: "30", dep: "-0,03", ac: "4" },
    ],
    eficienciaData: [
      { trait: "CAR", top: "26", dep: "-0,05", ac: "65" },
      { trait: "IMS", top: "62", dep: "0,02", ac: "69" },
    ],
    pedigree: {
      title: "CAMPEÃO x HUNO",
      sire: {
        name: "D4685 DA MN (CAMPEÃO)",
        registro: "",
        siresSire: "B9707 DA MN",
        siresDam: "C1454 DA MN",
      },
      dam: {
        name: "D1342 DA MN",
        registro: "",
        damsSire: "D1484 DA MN (HUNO)",
        damsDam: "C4580 DA MN (KONAN)",
      },
    },
  },
  wantuck: {
    id: "wantuck",
    code: "001NE00909",
    name: "WANTUCK G.SALES",
    fullName: "WANTUCK G.SALES",
    serieRgd: "MFBN 12100",
    nasc: "31/10/2023",
    proprietario: "GABRIEL CLAUDIO DE SALES",
    imageUrl: "/WANTUCK_PHOTO.jpg",
    pregcheckBr: "--",
    pregcheckConf: "--",
    badges: ["MATERNAL", "MARMOREO", "CARCAÇA", "PRECOCIDADE SEXUAL", "EFICIÊNCIA ALIMENTAR"],
    progenieData: {
      nf120: "0",
      nr120: "0",
      nf450: "0",
      nr450: "0",
    },
    indiceData: {
      mgte: { top: "4", dep: "25,87", ac: "53" },
    },
    producaoData: [
      { trait: "PN", top: "75", dep: "0,88", ac: "62" },
      { trait: "P120", top: "12", dep: "6,13", ac: "56" },
      { trait: "P210", top: "11", dep: "10,82", ac: "58" },
      { trait: "P365", top: "6", dep: "23,95", ac: "61" },
      { trait: "P450", top: "8", dep: "22,53", ac: "63" },
      { trait: "PAV", top: "41", dep: "27,23", ac: "25" },
    ],
    maternalData: [
      { trait: "MP120", top: "18", dep: "2,27", ac: "41" },
      { trait: "MP210", top: "15", dep: "3,39", ac: "41" },
      { trait: "IPP", top: "26", dep: "-0,68", ac: "34" },
      { trait: "3P", top: "13", dep: "83,07", ac: "52" },
      { trait: "STAY", top: "4", dep: "88,53", ac: "45" },
      { trait: "PAC", top: "22", dep: "6,09", ac: "20" },
      { trait: "PE365", top: "6", dep: "1,32", ac: "59" },
    ],
    carcacaData: [
      { trait: "AOL", top: "0.5", dep: "5,90", ac: "58" },
      { trait: "ACAB", top: "2", dep: "0,93", ac: "55" },
      { trait: "MARM", top: "4", dep: "0,14", ac: "50" },
      { trait: "MAC", top: "62", dep: "0,02", ac: "3" },
    ],
    eficienciaData: [
      { trait: "CAR", top: "28", dep: "-0,04", ac: "28" },
      { trait: "IMS", top: "21", dep: "-0,14", ac: "31" },
    ],
    pedigree: {
      title: "IUIU x QHELLI",
      sire: {
        name: "IUIU FIV DA BELA",
        registro: "",
        siresSire: "REM ARMADOR",
        siresDam: "TABAL FIV DA BELA",
      },
      dam: {
        name: "QHELLI G.SALES",
        registro: "",
        damsSire: "GANGES COL",
        damsDam: "NAVIOLA G.SALES",
      },
    },
  },
  tenente: {
    id: "tenente",
    code: "001NE00862",
    name: "TENENTE DA TERRA BRAVA",
    fullName: "6140 FIV DA TERRA BRAVA",
    serieRgd: "EFIF 6140",
    nasc: "11/11/2022",
    proprietario: "EDUARDO PINHEIRO CAMPOS / FERNANDO APARECIDO ESCOVAR / MARIANA MUNDIM ALVES GOMES / CAROLINE ATILIO DE FREITAS / MARIANA SANTOS TEZZO",
    imageUrl: "/TENENTE_PHOTO.jpg",
    pregcheckBr: "--",
    pregcheckConf: "--",
    badges: ["MATERNAL", "MARMOREIO", "CARCAÇA", "PRECOCIDADE SEXUAL"],
    progenieData: {
      nf120: "0",
      nr120: "0",
      nf450: "0",
      nr450: "0",
    },
    indiceData: {
      mgte: { top: "2", dep: "27,28", ac: "54" },
    },
    producaoData: [
      { trait: "PN", top: "52", dep: "0,51", ac: "60" },
      { trait: "P120", top: "19", dep: "4,81", ac: "54" },
      { trait: "P210", top: "13", dep: "10,01", ac: "56" },
      { trait: "P365", top: "11", dep: "19,86", ac: "59" },
      { trait: "P450", top: "12", dep: "19,60", ac: "62" },
      { trait: "PAV", top: "39", dep: "25,25", ac: "25" },
    ],
    maternalData: [
      { trait: "MP120", top: "4", dep: "4,06", ac: "39" },
      { trait: "MP210", top: "5", dep: "5,14", ac: "39" },
      { trait: "IPP", top: "3", dep: "-1,19", ac: "35" },
      { trait: "3P", top: "4", dep: "87,43", ac: "54" },
      { trait: "STAY", top: "0.5", dep: "94,10", ac: "47" },
      { trait: "PAC", top: "2", dep: "11,49", ac: "18" },
      { trait: "PE365", top: "0.5", dep: "2,08", ac: "56" },
    ],
    carcacaData: [
      { trait: "AOL", top: "2", dep: "4,90", ac: "61" },
      { trait: "ACAB", top: "1", dep: "1,13", ac: "60" },
      { trait: "MARM", top: "1", dep: "0,21", ac: "57" },
      { trait: "MAC", top: "56", dep: "0,01", ac: "3" },
    ],
    eficienciaData: [
      { trait: "CAR", top: "32", dep: "-0,03", ac: "30" },
      { trait: "IMS", top: "66", dep: "0,04", ac: "33" },
    ],
    pedigree: {
      title: "PORTO x 4577",
      sire: {
        name: "2954 FIV DA TERRA BRAVA (PORTO)",
        registro: "",
        siresSire: "REM EL DOURADO",
        siresDam: "1963 FIV TERRA BRAVA",
      },
      dam: {
        name: "4577 DA TERRA BRAVA",
        registro: "",
        damsSire: "REM GURU GENÉTICA ADITIVA",
        damsDam: "1650 FIV TERRA BRAVA",
      },
    },
  },
  linear: {
    id: "linear",
    code: "001NM00012",
    name: "LINEAR DA BOTICAO",
    fullName: "LINEAR DA BOTICAO",
    serieRgd: "BOM 3293",
    nasc: "17/10/2019",
    proprietario: "FLÁVIO AUGUSTO COTRIM FERREIRA / NELSTAR CRIADORES LTDA.",
    imageUrl: "/LINEAR_BOTICAO_PHOTO.jpg",
    pregcheckBr: "101",
    pregcheckConf: "83",
    badges: ["CARCAÇA"],
    progenieData: {
      nf120: "13",
      nr120: "3",
      nf450: "4",
      nr450: "1",
    },
    indiceData: {
      mgte: { top: "18", dep: "17,52", ac: "45" },
    },
    producaoData: [
      { trait: "PN", top: "96", dep: "1,63", ac: "62" },
      { trait: "P120", top: "3", dep: "9,11", ac: "53" },
      { trait: "P210", top: "4", dep: "14,32", ac: "55" },
      { trait: "P365", top: "8", dep: "22,39", ac: "58" },
      { trait: "P450", top: "8", dep: "22,28", ac: "59" },
      { trait: "PE365", top: "38", dep: "0,26", ac: "53" },
      { trait: "PE450", top: "47", dep: "0,15", ac: "55" },
    ],
    maternalData: [
      { trait: "MP120", top: "9", dep: "3,19", ac: "39" },
      { trait: "MP210", top: "13", dep: "3,68", ac: "39" },
      { trait: "IPP", top: "50", dep: "-0,42", ac: "33" },
      { trait: "3P", top: "54", dep: "73,62", ac: "36" },
      { trait: "PG", top: "72", dep: "1,02", ac: "56" },
      { trait: "STAY", top: "70", dep: "58,19", ac: "31" },
      { trait: "PAC", top: "25", dep: "5,60", ac: "20" },
    ],
    carcacaData: [
      { trait: "AOL", top: "21", dep: "1,68", ac: "52" },
      { trait: "ACAB", top: "6", dep: "0,51", ac: "48" },
      { trait: "MARM", top: "99", dep: "-0,25", ac: "42" },
    ],
    eficienciaData: [],
    pedigree: {
      title: "HIDROGENIO x FAIXA",
      sire: {
        name: "HIDROGENIO DA BOTICAO",
        registro: "",
        siresSire: "REM USP",
        siresDam: "ERIGIE DA BOTICAO",
      },
      dam: {
        name: "FAIXA DA BOTICAO",
        registro: "",
        damsSire: "QUARARACA 34 DA BACURI",
        damsDam: "NOTICIA 14 DA BOTICAO",
      },
    },
  },
}
